using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Qorpe.Mediator.SourceGenerator;

/// <summary>
/// Emits a compile-time, trimming/Native-AOT-safe registration method
/// <c>AddQorpeMediatorGenerated()</c> that registers all discovered handlers in DI and precomputes
/// the mediator dispatch (no assembly scanning, no runtime code generation).
/// </summary>
[Generator(Microsoft.CodeAnalysis.LanguageNames.CSharp)]
public sealed class MediatorRegistrationGenerator : IIncrementalGenerator
{
    private const string Abstractions = "Qorpe.Mediator.Abstractions";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var handlers = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax or RecordDeclarationSyntax { BaseList: not null } || node is ClassDeclarationSyntax { BaseList: not null },
                transform: static (ctx, _) => GetHandlerModels(ctx))
            .Where(static m => m is not null && m!.Length > 0)
            .SelectMany(static (m, _) => m!);

        var collected = handlers.Collect();

        context.RegisterSourceOutput(collected, static (spc, models) => Emit(spc, models));
    }

    private static HandlerModel[]? GetHandlerModels(GeneratorSyntaxContext ctx)
    {
        if (ctx.Node is not TypeDeclarationSyntax tds)
        {
            return null;
        }

        if (ctx.SemanticModel.GetDeclaredSymbol(tds) is not INamedTypeSymbol symbol)
        {
            return null;
        }

        if (symbol.IsAbstract || symbol.TypeKind == TypeKind.Interface || symbol.IsGenericType)
        {
            return null;
        }

        var models = new System.Collections.Generic.List<HandlerModel>();
        var fqf = SymbolDisplayFormat.FullyQualifiedFormat;
        var implName = symbol.ToDisplayString(fqf);

        foreach (var iface in symbol.AllInterfaces)
        {
            if (iface.ContainingNamespace?.ToDisplayString() != Abstractions || !iface.IsGenericType)
            {
                continue;
            }

            var def = iface.OriginalDefinition.Name; // e.g. IRequestHandler
            var args = iface.TypeArguments;

            switch (def)
            {
                case "IRequestHandler" when args.Length == 2:
                    models.Add(new HandlerModel(HandlerKind.Request, implName,
                        iface.ToDisplayString(fqf), args[0].ToDisplayString(fqf), args[1].ToDisplayString(fqf)));
                    break;
                case "IStreamRequestHandler" when args.Length == 2:
                    models.Add(new HandlerModel(HandlerKind.Stream, implName,
                        iface.ToDisplayString(fqf), args[0].ToDisplayString(fqf), args[1].ToDisplayString(fqf)));
                    break;
                case "INotificationHandler" when args.Length == 1:
                    models.Add(new HandlerModel(HandlerKind.Notification, implName,
                        iface.ToDisplayString(fqf), args[0].ToDisplayString(fqf), null));
                    break;
                case "IPipelineBehavior" when args.Length == 2:
                case "IStreamPipelineBehavior" when args.Length == 2:
                case "IRequestPreProcessor" when args.Length == 1:
                case "IRequestPostProcessor" when args.Length == 2:
                    models.Add(new HandlerModel(HandlerKind.MultiInstance, implName,
                        iface.ToDisplayString(fqf), null, null));
                    break;
            }
        }

        return models.Count == 0 ? null : models.ToArray();
    }

    private static void Emit(SourceProductionContext spc, ImmutableArray<HandlerModel> models)
    {
        if (models.IsDefaultOrEmpty)
        {
            return;
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection.Extensions;");
        sb.AppendLine();
        sb.AppendLine("namespace Qorpe.Mediator");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Source-generated, AOT-safe mediator registration.</summary>");
        sb.AppendLine("    public static class GeneratedMediatorRegistration");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>Registers all discovered handlers and precomputes dispatch (no scanning).</summary>");
        sb.AppendLine("        public static IServiceCollection AddQorpeMediatorGenerated(this IServiceCollection services, global::System.Action<global::Qorpe.Mediator.DependencyInjection.MediatorOptions>? configure = null)");
        sb.AppendLine("        {");
        sb.AppendLine("            var options = new global::Qorpe.Mediator.DependencyInjection.MediatorOptions();");
        sb.AppendLine("            configure?.Invoke(options);");
        sb.AppendLine("            global::Qorpe.Mediator.DependencyInjection.ServiceCollectionExtensions.AddQorpeMediatorCore(services, options);");
        sb.AppendLine();

        var dispatchedRequests = new System.Collections.Generic.HashSet<string>();
        var dispatchedNotifications = new System.Collections.Generic.HashSet<string>();
        var dispatchedStreams = new System.Collections.Generic.HashSet<string>();
        var registeredDi = new System.Collections.Generic.HashSet<string>();

        foreach (var m in models)
        {
            switch (m.Kind)
            {
                case HandlerKind.Request:
                    if (registeredDi.Add(m.ServiceType + "|" + m.ImplType))
                    {
                        sb.AppendLine($"            services.TryAddTransient<{m.ServiceType}, {m.ImplType}>();");
                    }
                    if (dispatchedRequests.Add(m.Arg0 + "|" + m.Arg1))
                    {
                        sb.AppendLine($"            global::Qorpe.Mediator.Implementation.Mediator.RegisterSend<{m.Arg0}, {m.Arg1}>();");
                    }
                    break;

                case HandlerKind.Stream:
                    if (registeredDi.Add(m.ServiceType + "|" + m.ImplType))
                    {
                        sb.AppendLine($"            services.TryAddTransient<{m.ServiceType}, {m.ImplType}>();");
                    }
                    if (dispatchedStreams.Add(m.Arg0 + "|" + m.Arg1))
                    {
                        sb.AppendLine($"            global::Qorpe.Mediator.Implementation.Mediator.RegisterStream<{m.Arg0}, {m.Arg1}>();");
                    }
                    break;

                case HandlerKind.Notification:
                    sb.AppendLine($"            services.TryAddEnumerable(ServiceDescriptor.Transient<{m.ServiceType}, {m.ImplType}>());");
                    if (dispatchedNotifications.Add(m.Arg0!))
                    {
                        sb.AppendLine($"            global::Qorpe.Mediator.Implementation.Mediator.RegisterNotification<{m.Arg0}>();");
                    }
                    break;

                case HandlerKind.MultiInstance:
                    sb.AppendLine($"            services.TryAddEnumerable(ServiceDescriptor.Transient<{m.ServiceType}, {m.ImplType}>());");
                    break;
            }
        }

        sb.AppendLine();
        sb.AppendLine("            return services;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        spc.AddSource("GeneratedMediatorRegistration.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private enum HandlerKind
    {
        Request,
        Stream,
        Notification,
        MultiInstance,
    }

    private sealed class HandlerModel
    {
        public HandlerModel(HandlerKind kind, string implType, string serviceType, string? arg0, string? arg1)
        {
            Kind = kind;
            ImplType = implType;
            ServiceType = serviceType;
            Arg0 = arg0;
            Arg1 = arg1;
        }

        public HandlerKind Kind { get; }
        public string ImplType { get; }
        public string ServiceType { get; }
        public string? Arg0 { get; }
        public string? Arg1 { get; }
    }
}
