<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Mediant/Mediant.csproj" />
    <ProjectReference Include="../../src/Mediant.Behaviors/Mediant.Behaviors.csproj" />
    <ProjectReference Include="../../src/Mediant.FluentValidation/Mediant.FluentValidation.csproj" />
    <ProjectReference Include="../../src/Mediant.AspNetCore/Mediant.AspNetCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.11.0" />
  </ItemGroup>

</Project>
